config/routes.rb
Auth::Application.routes.draw do
  resources :admins
  resources :sessions
  resources :users, except: [:new] do
    resource :profile #, path_names: { edit: '' }, only: [ :index, :show, :edit, :update ]
  end
  get "sign_up" => "users#new", as: "sign_up"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  
  root :to => "users#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
  	admin = find_by_email(email)
  	if admin && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  		admin
  	else
  		nil
  	end
  end

 def encrypt_password
 	if password.present?
 		self.password_salt = BCrypt::Engine.generate_salt
 		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
 	end
 end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :first_name, :last_name, :age, :birth_date

  validates_confirmation_of :first_name, :last_name, :age, :birth_date
  validates_presence_of :first_name, :last_name, :age, :birth_date

  def in(first_name, last_name, age, birth_date)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile

  attr_accessible :email, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  		user
  	else
  		nil
  	end
  end

 def encrypt_password
 	if password.present?
 		self.password_salt = BCrypt::Engine.generate_salt
 		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
 	end
 end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/new
  # GET /admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(params[:admin])

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admins/1
  # PUT /admins/1.json
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(params[:admin])
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @user = User.find(params[:id])
    @user.destroy
    @admin.destroy

    respond_to do |format|
      redirect_to user_url(:session[:user_id])
      format.html { redirect_to admins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_admin
		@current_admin ||= Admin.find(admin[:admin]) if admin[:admin]
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def show
    @profile = Profile.find(params[:user_id])
  end

  def new
    @profile = Profile.new(params[:user_id])
  end

  def edit
    @profile = User.find(params[:user_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	@user = User.authenticate(params[:email], params[:password])
  	if @user
  		session[:user_id] = @user.id
  		redirect_to edit_user_profile_path(@user.id), notice: "Logged In!"
  	else
  		flash.now.alert = "Invalid email or password!"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to root_url, notice: "Signed Up!"
  	else
  		render "new"
  	end
	end

  def edit
    @user = User.find(params[:id])
    @user = current_user(@user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Edit Successful."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to root_url, notice: "User deleted."
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
  <p>
    <%= f.label :email %> <br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %> <br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %> <br />
    <%= f.password_field :password_confirmation %>
  </p>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing users</h1>
<table>
<% @users.each do |user| %>
  <tr>
    <th><%= user.email %></th>
    <th>
    <%=button_to 'Delete User', user, controller: "users", action: "destroy", id: user.id, confirm: "Are you sure?", method: :delete %>
    </th>
  </tr>
<% end %>
</table>

<table>
<% @admins.each do |admin| %>
  <tr>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>Auth</title>
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="user_nav">
			<% if current_user %>
				Logged in as <%= current_user.email %>
				<%= link_to "Log out", log_out_path %>
				<%= link_to "Edit", edit_user_profile_path(current_user) %>

			<% else %>
				<%= link_to "Sign up", sign_up_path %>
				<%= link_to "Log in", log_in_path %>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
		<%= yield %>
	</body>
</html>

app/views/profiles/edit.html.erb
<h1>Profile</h1>
<%= form_for @profile do |f| %>
	<% if @profile.errors.any? %>
		<div class="errors_messages">
			<h2> Form is invalid </h2>
			<ul>
				<% @profile.errors.full_messages.each do |message| %>
					<li> <%= message %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :first_name %> <br />
		<%= f.text_field :first_name %>
	</p>

	<p class="actions"><%= f.submit %></p>
<% end %>

app/views/profiles/show.html.erb
lal 

app/views/profiles/update.html.erb
lol

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="errors_messages">
			<h2> Form is invalid </h2>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li> <%= message %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>
  <div class="field">
    <%= f.label :email %>    
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1> Your regestration </h1>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="errors_messages">
			<h2> Form is invalid </h2>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li> <%= message %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %> <br />
		<%= f.password_field :password_confirmation %>
	</p>
	<p class="actions"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h2> Your email was changed! </h2>
<%= link_to "Home page", edit_user_profile_path(@user.id) %><br />